import React, { useEffect, useState } from "react";
import Head from "next/head";
import { motion, useScroll } from "framer-motion";

// components
import HomeContents from "@/contents/Home";

export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeContents />
    </>
  );
}
